#pragma once

#include "ExteriorCellRecord.h"
#include "WorldspaceGroupPlan.h"

#include <cstdint>

// Read-only lookup of records that have already been generated by the compiler.
// The worldspace group serializer never recreates those records.
class IGeneratedRecordRepository {
public:
    virtual ~IGeneratedRecordRepository() = default;

    [[nodiscard]] virtual const ExteriorCellRecord& GetCell(std::uint32_t formID) const = 0;
    [[nodiscard]] virtual const LandRecord& GetLand(std::uint32_t formID) const = 0;
    [[nodiscard]] virtual const ReferenceRecord& GetReference(std::uint32_t formID) const = 0;
};
